cache: yarn
matrix:
  include:
    - language: node_js
      node_js:
        - "8"
        - "10"
      script:
        - ./scripts/test-travis.sh
      cache: yarn
      git:
        depth: 5

    - language: node_js
      node_js: "8"
      stage: integ
      script:
        - yarn test-integ
      git:
        depth: 5
